"use client";

import { motion, useReducedMotion } from "framer-motion";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";

const ALTS = [
  "at the Palace of Fine Arts",
  "with a golden retriever",
  "holding certificates with friends",
  "in a green frog hat",
  "with friends overlooking a city at dusk",
  "with a friend in Yosemite",
  "at graduation with friends",
  "overlooking a city at night",
  "with friends holding snacks",
  "as a child in sunglasses",
  "with friends in a sunlit hall",
  "with a dog outside her high school",
  "hugging a friend at sunset",
  "with a friend at home",
  "with friends on a hill at dusk",
  "with a friend in a grand hall",
  "by balloon palm trees",
  "at a concert with a friend",
  "at dinner",
  "at graduation with family",
  "in a knit hat with friends",
  "at a formal with friends",
  "with a friend in a lobby",
  "with a friend at a formal under balloons",
];

// File numbers in /public/collage, in the same order as ALTS. Numbers are never reused,
// so a cached copy of a removed photo can't show up in place of a new one.
const FILES = [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 26];

// Per-photo framing, keyed by file number: print shape (width / height of the photo area),
// which part of the photo shows, and zoom.
const FRAMING: Record<number, { aspect?: number; position?: string; zoom?: number }> = {
  3: { aspect: 1.5 }, // certificates: whole picture
  7: { position: "27% 30%" }, // graduation: even space on both sides
  13: { position: "100% 25%", zoom: 1.15 }, // Falcons sign: trim the empty left side
  18: { zoom: 1.1 }, // balloon palm trees
  19: { aspect: 4 / 3 }, // concert: whole picture
  21: { aspect: 1.25, position: "10% 30%" }, // family graduation: wider so no one is cut off
};

export const PHOTOS = ALTS.map((alt, i) => ({
  src: `/collage/photo-${String(FILES[i]).padStart(2, "0")}.jpg`,
  alt: `Veronica ${alt}`,
  aspect: FRAMING[FILES[i]]?.aspect ?? 1,
  position: FRAMING[FILES[i]]?.position ?? "center 30%",
  zoom: FRAMING[FILES[i]]?.zoom ?? 1,
}));

// Generated by a seeded packing script: freeform positions with no overlaps.
// left/top/width are % of the board; rotate is degrees. One layout per board shape.
export const LAYOUTS = {
  wide: [
    { left: 8.77, top: 5.02, width: 8.9, rotate: -8.4 },
    { left: 20.05, top: 76.59, width: 11.45, rotate: -10.3 },
    { left: 57.18, top: 55.37, width: 11.11, rotate: -3.2 },
    { left: 41.69, top: 57.8, width: 9.67, rotate: 0.2 },
    { left: 32.61, top: 27.91, width: 11.05, rotate: -1.6 },
    { left: 86.2, top: 59.31, width: 9.22, rotate: -9.8 },
    { left: 41.07, top: 5.23, width: 10.77, rotate: 7.8 },
    { left: 37.65, top: 77.85, width: 11.38, rotate: 10.7 },
    { left: 86.97, top: 7.42, width: 11.23, rotate: -2.5 },
    { left: 62.65, top: 25.88, width: 12.43, rotate: -10.9 },
    { left: 2.2, top: 23.85, width: 12.08, rotate: -5.0 },
    { left: 71.51, top: 49.82, width: 9.93, rotate: -9.2 },
    { left: 71.23, top: 71.13, width: 10.43, rotate: 7.6 },
    { left: 59.45, top: 5.46, width: 10.04, rotate: 2.0 },
    { left: 84.57, top: 76.4, width: 11.42, rotate: -3.1 },
    { left: 85.12, top: 37.56, width: 11.14, rotate: -10.5 },
    { left: 72.13, top: 3.77, width: 12.1, rotate: -7.1 },
    { left: 56.03, top: 80.28, width: 11.54, rotate: -1.7 },
    { left: 48.02, top: 26.16, width: 10.44, rotate: 2.1 },
    { left: 22.09, top: 4.33, width: 10.86, rotate: -4.8 },
    { left: 3.7, top: 78.84, width: 11.88, rotate: 4.8 },
    { left: 17.74, top: 28.27, width: 10.23, rotate: 1.8 },
    { left: 3.83, top: 51.06, width: 11.08, rotate: 9.0 },
    { left: 20.26, top: 49.6, width: 10.65, rotate: 10.6 },
  ],
  narrow: [
    { left: 72.32, top: 21.2, width: 12.67, rotate: 11.1 },
    { left: 80.84, top: 3.31, width: 14.51, rotate: 4.9 },
    { left: 65.65, top: 88.59, width: 14.34, rotate: -6.1 },
    { left: 10.13, top: 60.15, width: 18.0, rotate: -7.0 },
    { left: 36.98, top: 72.58, width: 17.89, rotate: -1.0 },
    { left: 41.31, top: 85.75, width: 15.81, rotate: -0.1 },
    { left: 11.39, top: 46.42, width: 14.77, rotate: 7.9 },
    { left: 48.62, top: 17.25, width: 14.08, rotate: -5.6 },
    { left: 46.97, top: 60.06, width: 15.63, rotate: 9.6 },
    { left: 41.79, top: 29.87, width: 15.52, rotate: -9.3 },
    { left: 41.73, top: 45.13, width: 15.03, rotate: 11.8 },
    { left: 24.73, top: 86.87, width: 14.25, rotate: 2.9 },
    { left: 3.04, top: 4.38, width: 15.51, rotate: 3.9 },
    { left: 55.41, top: 4.71, width: 15.35, rotate: 4.6 },
    { left: 4.77, top: 87.4, width: 15.99, rotate: 3.6 },
    { left: 80.28, top: 74.56, width: 17.61, rotate: 2.0 },
    { left: 59.73, top: 75.29, width: 16.76, rotate: -10.5 },
    { left: 29.57, top: 1.64, width: 17.78, rotate: -0.3 },
    { left: 9.76, top: 18.05, width: 14.78, rotate: 10.7 },
    { left: 9.48, top: 31.48, width: 16.32, rotate: 5.5 },
    { left: 72.93, top: 37.69, width: 17.52, rotate: -5.1 },
    { left: 81.79, top: 56.8, width: 15.43, rotate: 9.1 },
    { left: 31.3, top: 16.51, width: 14.54, rotate: 6.3 },
    { left: 19.07, top: 74.77, width: 15.31, rotate: 10.3 },
  ],
};

export const LIGHTS_WIDE = [[0.0, 0], [6.25, 0], [12.5, 0], [18.75, 0], [25.0, 0], [31.25, 0], [37.5, 0], [43.75, 0], [50.0, 0], [56.25, 0], [62.5, 0], [68.75, 0], [75.0, 0], [81.25, 0], [87.5, 0], [93.75, 0], [100, 0.0], [100, 9.09], [100, 18.18], [100, 27.27], [100, 36.36], [100, 45.45], [100, 54.55], [100, 63.64], [100, 72.73], [100, 81.82], [100, 90.91], [100.0, 100], [93.75, 100], [87.5, 100], [81.25, 100], [75.0, 100], [68.75, 100], [62.5, 100], [56.25, 100], [50.0, 100], [43.75, 100], [37.5, 100], [31.25, 100], [25.0, 100], [18.75, 100], [12.5, 100], [6.25, 100], [0, 100.0], [0, 90.91], [0, 81.82], [0, 72.73], [0, 63.64], [0, 54.55], [0, 45.45], [0, 36.36], [0, 27.27], [0, 18.18], [0, 9.09]] as const;

export const LIGHTS_NARROW = [[0.0, 0], [11.11, 0], [22.22, 0], [33.33, 0], [44.44, 0], [55.56, 0], [66.67, 0], [77.78, 0], [88.89, 0], [100, 0.0], [100, 6.67], [100, 13.33], [100, 20.0], [100, 26.67], [100, 33.33], [100, 40.0], [100, 46.67], [100, 53.33], [100, 60.0], [100, 66.67], [100, 73.33], [100, 80.0], [100, 86.67], [100, 93.33], [100.0, 100], [88.89, 100], [77.78, 100], [66.67, 100], [55.56, 100], [44.44, 100], [33.33, 100], [22.22, 100], [11.11, 100], [0, 100.0], [0, 93.33], [0, 86.67], [0, 80.0], [0, 73.33], [0, 66.67], [0, 60.0], [0, 53.33], [0, 46.67], [0, 40.0], [0, 33.33], [0, 26.67], [0, 20.0], [0, 13.33], [0, 6.67]] as const;

// "Seaglass kiss" palette.
const PIN_COLORS = ["#E8B86C", "#FDD6CF", "#FDADA4", "#A880A0", "#619394"];

export const BOARD_IN = 0.45; // board fades in
export const PHOTO_STAGGER = 0.055;
export const FLIGHT = 0.75;
export const PIN_TIME = 0.4;
// When the last pin is stuck in.
export const PINNED = BOARD_IN + PHOTO_STAGGER * (PHOTOS.length - 1) + FLIGHT + PIN_TIME;
export const BOARD_FULL = 0.72; // a touch see-through so it isn't glaring on the dark page
export const BOARD_DIM = 0.32;

// Small deterministic pseudo-random numbers in [0, 1) for twinkle timing.
function rand(seed: number) {
  const x = Math.sin(seed * 12.9898) * 43758.5453;
  return x - Math.floor(x);
}

function Pin({ color, delay, play, reduce }: { color: string; delay: number; play: boolean; reduce: boolean }) {
  return (
    // Sits on the print's top white border.
    <span aria-hidden="true" className="top-0 left-1/2 z-10 absolute size-[clamp(8px,1.2vw,12px)] -translate-x-1/2 -translate-y-[20%]">
      {/* Shadow: wide and offset while the pin is in the air, tight once it's stuck in. */}
      <motion.span
        className="absolute inset-0 bg-black/45 blur-[1.5px] rounded-full"
        initial={{ opacity: 0, x: 14, y: 16, scale: 1.8 }}
        animate={play ? { opacity: 1, x: 1.5, y: 2.5, scale: 1 } : undefined}
        transition={reduce ? { duration: 0 } : { delay, duration: PIN_TIME * 0.7, ease: [0.5, 0, 0.75, 0] }}
      />
      {/* Head: drops from above, shrinking as it approaches, then squashes on impact. */}
      <motion.span
        className="absolute inset-0 rounded-full"
        style={{
          background: `radial-gradient(circle at 35% 30%, #ffffffcc 0 16%, ${color} 24%, ${color} 70%, #0000004d 100%)`,
        }}
        initial={{ opacity: 0, y: -42, scale: 2.2 }}
        animate={play ? { opacity: 1, y: 0, scale: [2.2, 1, 0.82, 1] } : undefined}
        transition={
          reduce
            ? { duration: 0 }
            : {
                y: { delay, duration: PIN_TIME * 0.7, ease: [0.5, 0, 0.75, 0] },
                scale: { delay, duration: PIN_TIME, times: [0, 0.7, 0.85, 1] },
                opacity: { delay, duration: 0.08 },
              }
        }
      />
    </span>
  );
}

// A thin wire with little star bulbs around the board's border. It sits outside the
// board's fade, so the lights keep glowing after the board dims.
function StringLights({
  points,
  play,
  reduce,
}: {
  points: readonly (readonly [number, number])[];
  play: boolean;
  reduce: boolean;
}) {
  // The wire droops slightly inward between bulbs.
  const path = points
    .map(([x, y], i) => {
      const [nx, ny] = points[(i + 1) % points.length];
      const mx = (x + nx) / 2;
      const my = (y + ny) / 2;
      const sagX = x === 0 && nx === 0 ? 1.2 : x === 100 && nx === 100 ? -1.2 : 0;
      const sagY = y === 0 && ny === 0 ? 1.2 : y === 100 && ny === 100 ? -1.2 : 0;
      return `${i === 0 ? `M ${x} ${y} ` : ""}Q ${mx + sagX} ${my + sagY} ${nx} ${ny}`;
    })
    .join(" ");

  return (
    <div aria-hidden="true" className="z-20 absolute inset-0 pointer-events-none">
      <motion.svg
        className="absolute inset-0 overflow-visible size-full"
        viewBox="0 0 100 100"
        preserveAspectRatio="none"
        initial={{ opacity: 0 }}
        animate={play ? { opacity: 1 } : undefined}
        transition={reduce ? { duration: 0 } : { duration: BOARD_IN }}
      >
        <path d={path} fill="none" stroke="#4a4d3c" strokeWidth={1.2} vectorEffect="non-scaling-stroke" />
      </motion.svg>

      {points.map(([x, y], i) => (
        <motion.span
          key={i}
          className="absolute size-[clamp(9px,1.15vw,13px)] -translate-x-1/2 -translate-y-1/2"
          style={{ left: `${x}%`, top: `${y}%` }}
          initial={{ opacity: 0, scale: 0 }}
          animate={play ? { opacity: 1, scale: 1 } : undefined}
          // Switch on one after another, around the board.
          transition={reduce ? { duration: 0 } : { delay: 0.15 + i * 0.018, duration: 0.3, ease: "backOut" }}
        >
          <svg
            viewBox="0 0 24 24"
            className="size-full twinkle"
            style={{
              rotate: `${Math.round((rand(i + 7) - 0.5) * 50)}deg`,
              animationDuration: `${(1.6 + rand(i + 31) * 1.8).toFixed(2)}s`,
              animationDelay: `${(rand(i + 59) * 2).toFixed(2)}s`,
              filter: "drop-shadow(0 0 3px rgba(255,220,140,0.95)) drop-shadow(0 0 9px rgba(255,190,90,0.6))",
            }}
          >
            <path d="M12 1.5l3.1 6.6 7.2.9-5.3 5 1.4 7.1L12 17.6l-6.4 3.5 1.4-7.1-5.3-5 7.2-.9z" fill="#ffe6a3" />
          </svg>
        </motion.span>
      ))}
    </div>
  );
}

export function CollageBoard({ onStart }: { onStart?: () => void }) {
  const reduce = Boolean(useReducedMotion());
  const [loaded, setLoaded] = useState(0);
  const [play, setPlay] = useState(false);
  const [travel, setTravel] = useState(1400);
  const [narrow, setNarrow] = useState(false);
  const onStartRef = useRef(onStart);
  onStartRef.current = onStart;

  // Tall layout for phones (matches the board's sm: breakpoint).
  useEffect(() => {
    const mq = window.matchMedia("(max-width: 639px)");
    const update = () => setNarrow(mq.matches);
    update();
    mq.addEventListener("change", update);
    return () => mq.removeEventListener("change", update);
  }, []);

  // Start once the photos have loaded, or after a short timeout on slow connections.
  useEffect(() => {
    if (play) return;
    const go = () => {
      setTravel(Math.max(window.innerWidth, window.innerHeight) * 1.1);
      setPlay(true);
      onStartRef.current?.();
    };
    if (reduce || loaded >= PHOTOS.length) return go();
    const t = window.setTimeout(go, 2500);
    return () => window.clearTimeout(t);
  }, [loaded, reduce, play]);

  const layout = narrow ? LAYOUTS.narrow : LAYOUTS.wide;
  const total = PINNED + 0.9;

  return (
    <div className="relative">
      <motion.div
        className="relative shadow-[0_20px_60px_rgba(0,0,0,0.5)] rounded-xl w-full aspect-[0.62] sm:aspect-[1.36]"
        style={{
          backgroundColor: "#efe7d8",
          backgroundImage:
            "radial-gradient(rgba(120,95,60,0.10) 1px, transparent 1.2px), radial-gradient(rgba(120,95,60,0.06) 1px, transparent 1.2px)",
          backgroundSize: "7px 7px, 11px 11px",
          backgroundPosition: "0 0, 3px 5px",
        }}
        initial={{ opacity: 0, scale: 0.97 }}
        animate={play ? { opacity: [0, BOARD_FULL, BOARD_FULL, BOARD_DIM], scale: 1 } : undefined}
        transition={
          reduce
            ? { duration: 0 }
            : {
                // Fade in, hold while photos are pinned, then dim behind the greeting.
                opacity: { duration: total, times: [0, BOARD_IN / total, PINNED / total, 1] },
                scale: { duration: BOARD_IN, ease: "easeOut" },
              }
        }
      >
        {PHOTOS.map((photo, i) => {
          const spot = layout[i];
          // Spread the entry directions around the circle (golden angle).
          const angle = (i * 137.5 * Math.PI) / 180;
          const delay = BOARD_IN + i * PHOTO_STAGGER;
          const pinAt = delay + FLIGHT;
          const spin = (i % 2 === 0 ? 1 : -1) * (25 + ((i * 7) % 20));

          return (
            <motion.div
              key={photo.src}
              className="absolute"
              style={{
                left: `${spot.left}%`,
                top: `${spot.top}%`,
                width: `${spot.width}%`,
                transition: "left 0.5s, top 0.5s, width 0.5s",
              }}
              initial={{
                // Rounded so the server and browser render identical styles.
                x: Math.round(Math.cos(angle) * travel),
                y: Math.round(Math.sin(angle) * travel),
                scale: 2.4,
                rotate: spot.rotate + spin,
                opacity: 0,
              }}
              animate={play ? { x: 0, y: 0, scale: 1, rotate: spot.rotate, opacity: 1 } : undefined}
              transition={
                reduce
                  ? { duration: 0 }
                  : { delay, duration: FLIGHT, ease: [0.16, 1, 0.3, 1], opacity: { delay, duration: 0.2 } }
              }
            >
              {/* Dips slightly when its pin goes in. */}
              <motion.div
                className="bg-white shadow-[0_3px_8px_rgba(60,40,10,0.35)] p-[6%] pb-[16%]"
                animate={play && !reduce ? { scale: [1, 1, 0.95, 1] } : undefined}
                transition={{ delay: pinAt, duration: PIN_TIME + 0.15, times: [0, 0.62, 0.78, 1] }}
              >
                <div className="relative w-full overflow-hidden" style={{ aspectRatio: photo.aspect }}>
                  <Image
                    src={photo.src}
                    alt={photo.alt}
                    fill
                    sizes="(max-width: 640px) 20vw, 140px"
                    className="object-cover"
                    style={{
                      objectPosition: photo.position,
                      transform: photo.zoom !== 1 ? `scale(${photo.zoom})` : undefined,
                      transformOrigin: photo.position,
                    }}
                    priority={i < 6}
                    onLoad={() => setLoaded((n) => n + 1)}
                  />
                </div>
              </motion.div>
              <Pin color={PIN_COLORS[i % PIN_COLORS.length]} delay={pinAt} play={play} reduce={reduce} />
            </motion.div>
          );
        })}
      </motion.div>

      <StringLights points={narrow ? LIGHTS_NARROW : LIGHTS_WIDE} play={play} reduce={reduce} />
    </div>
  );
}
